# Ann Arbor Inequality

The NYC Federal Reserve released a [paper](https://www.newyorkfed.org/medialibrary/media/research/epr/2019/epr_2019_wage-inequality_abel-deitz.pdf) on income inequality in Metropolitan Statistical Areas (MSAs), discussed [here](https://libertystreeteconomics.newyorkfed.org/2019/10/some-places-are-much-more-unequal-than-others.html) in a blog post.

Ann Arbor is ranked 14 out of the 15 most unequal MSAs in the country. I wanted to test whether this statistic included student incomes, and if this affected the inequality ratio.

In [1]:
import pandas as pd

I used the same data source as the Fed Study, IPUMS 2015 ACS data. The dataset I downloaded only contains individuals within the Ann Arbor MSA.

Ruggles, S., K. Genadek, R. Goeken, J. Grover, and M. Sobek. 2015. Integrated Public Use
Microdata Series: Version 6.0 [dataset]. Minneapolis: University of Minnesota. http://doi.org/10.18128/D010.V6.0

In [2]:
a2 = pd.read_csv("usa_00001.csv")

In [3]:
a2

,YEAR,SAMPLE,SERIAL,CBSERIAL,HHWT,MET2013,GQ,PERNUM,PERWT,SCHOOL,EMPSTAT,EMPSTATD,LABFORCE,INCWAGE
0,2015,201501,622532,2076,409,11460,1,1,409,1,1,10,2,114000
1,2015,201501,622532,2076,409,11460,1,2,129,1,1,10,2,23700
2,2015,201501,622532,2076,409,11460,1,3,329,2,0,0,0,999999
3,2015,201501,622540,2357,175,11460,1,1,176,1,3,30,1,0
4,2015,201501,622540,2357,175,11460,1,2,154,1,3,30,1,0
5,2015,201501,622542,2385,170,11460,1,1,170,1,2,20,2,53000
6,2015,201501,622548,2593,49,11460,1,1,50,1,1,10,2,50000
7,2015,201501,622575,3859,110,11460,1,1,109,1,3,30,1,700
8,2015,201501,622584,4115,120,11460,1,1,119,1,1,10,2,45000
9,2015,201501,622584,4115,120,11460,1,2,97,2,3,30,1,0
10,2015,201501,622584,4115,120,11460,1,3,145,2,0,0,0,999999
11,2015,201501,622587,4262,62,11460,4,1,62,2,1,10,2,14400
12,2015,201501,622594,4591,85,11460,1,1,85,1,1,10,2,35000
13,2015,201501,622594,4591,85,11460,1,2,99,1,3,30,1,0
14,2015,201501,622609,5161,95,11460,1,1,94,1,3,30,1,0
15,2015,201501,622618,5428,49,11460,1,1,49,1,1,10,2,4800
16,2015,201501,622689,7731,159,11460,1,1,159,1,3,30,1,0
17,2015,201501,622711,8444,49,11460,1,1,49,1,1,10,2,55000
18,2015,201501,622734,9238,19,11460,4,1,19,2,3,30,1,2500
19,2015,201501,622759,10322,167,11460,1,1,167,1,1,10,2,10000
20,2015,201501,622759,10322,167,11460,1,2,130,1,1,10,2,58000
21,2015,201501,622773,11099,65,11460,1,1,64,1,1,10,2,8100
22,2015,201501,622773,11099,65,11460,1,2,65,2,0,0,0,999999
23,2015,201501,622773,11099,65,11460,1,3,125,1,1,10,2,35000
24,2015,201501,622773,11099,65,11460,1,4,64,2,0,0,0,999999
25,2015,201501,622773,11099,65,11460,1,5,60,0,0,0,0,999999
26,2015,201501,622773,11099,65,11460,1,6,89,1,1,10,2,22000
27,2015,201501,622773,11099,65,11460,1,7,53,1,3,30,1,0
28,2015,201501,622783,11224,109,11460,1,1,109,1,1,10,2,68000
29,2015,201501,622783,11224,109,11460,1,2,100,1,1,10,2,81000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119,2015,201501,665860,1496375,65,11460,1,3,57,2,3,30,1,0
3120,2015,201501,665860,1496375,65,11460,1,4,84,2,0,0,0,999999
3121,2015,201501,665873,1496639,91,11460,4,1,91,2,3,30,1,4000
3122,2015,201501,665914,1498310,59,11460,4,1,59,2,3,30,1,5500
3123,2015,201501,665922,1498494,100,11460,1,1,100,1,3,30,1,0
3124,2015,201501,665930,1498802,10,11460,4,1,10,2,3,30,1,3000
3125,2015,201501,665933,1498848,30,11460,1,1,30,1,3,30,1,0
3126,2015,201501,665935,1498866,91,11460,1,1,92,1,1,10,2,160000
3127,2015,201501,665935,1498866,91,11460,1,2,85,1,1,10,2,180000
3128,2015,201501,665935,1498866,91,11460,1,3,61,2,3,30,1,4000
3129,2015,201501,665935,1498866,91,11460,1,4,81,2,0,0,0,999999
3130,2015,201501,665935,1498866,91,11460,1,5,135,2,0,0,0,999999
3131,2015,201501,665946,1499037,89,11460,1,1,88,1,1,10,2,17000
3132,2015,201501,665946,1499037,89,11460,1,2,113,1,1,10,2,15000
3133,2015,201501,665946,1499037,89,11460,1,3,85,2,0,0,0,999999
3134,2015,201501,665946,1499037,89,11460,1,4,89,2,0,0,0,999999
3135,2015,201501,666007,1501406,35,11460,1,1,35,1,3,30,1,0
3136,2015,201501,666007,1501406,35,11460,1,2,43,1,1,10,2,26000
3137,2015,201501,666007,1501406,35,11460,1,3,40,2,0,0,0,999999
3138,2015,201501,666007,1501406,35,11460,1,4,41,2,0,0,0,999999
3139,2015,201501,666007,1501406,35,11460,1,5,35,0,0,0,0,999999
3140,2015,201501,666007,1501406,35,11460,1,6,99,2,0,0,0,999999
3141,2015,201501,666007,1501406,35,11460,1,7,27,2,0,0,0,999999
3142,2015,201501,666149,1506402,130,11460,1,1,130,1,3,30,1,0
3143,2015,201501,666218,1508506,72,11460,1,1,73,1,1,10,2,44000
3144,2015,201501,666218,1508506,72,11460,1,2,72,2,3,30,1,0
3145,2015,201501,666280,1510556,89,11460,1,1,89,1,3,30,1,0
3146,2015,201501,666325,1512293,91,11460,4,1,91,2,3,30,1,3000
3147,2015,201501,666345,1512921,63,11460,1,1,62,1,1,10,2,60000
3148,2015,201501,666345,1512921,63,11460,1,2,51,1,1,10,2,36700

### School and Employment
To determine if there are potentially students in the wage data, I check the crosstab between school attendance and employment. 
#### School
| Value | Label             |
|-------|-------------------|
| 0     | N/A               |
| 1     | No, not in school |
| 2     | Yes, in school    |
| 9     | Missing           |

#### Empstat
| Value | Label              |
|-------|--------------------|
| 0     | N/A                |
| 1     | Employed           |
| 2     | Unemployed         |
| 3     | Not in Labor Force |

We want to see the intersection of School == 2 and Empstat == 1

In [5]:
pd.crosstab(a2.SCHOOL, a2.EMPSTAT)

EMPSTAT    0     1   2    3
SCHOOL
0         87     0   0    0
1         41  1281  44  690
2        365   308  28  305

There are 308 observations in the sample, so it is possible that the results are influenced.

### Student Population

In order to understand the potential impact, I measure the estimated number of students in the Ann Arbor MSA.

In [15]:
pop = a2.groupby("SCHOOL").sum()
pop["Pop Pct"] = pop["PERWT"]/pop["PERWT"].sum()*100
pop

,YEAR,SAMPLE,SERIAL,CBSERIAL,HHWT,MET2013,GQ,PERNUM,PERWT,EMPSTAT,EMPSTATD,LABFORCE,INCWAGE,Pop Pct
SCHOOL,,,,,,,,,,,,,,
0,175305,17530587,56087638,66719734,10389,997020,87,336,9866,0,0,0,86999913,2.755566
1,4142840,414286056,1324582655,1545816438,221638,23561760,2225,3297,228078,3439,34464,3340,121953359,63.701999
2,2027090,202710006,649240055,795112114,112967,11528760,1664,2504,120095,1279,12832,977,371750229,33.542435

Over 33% of Ann Arbor's population is students

### Wage Ratio

The original study uses a ratio of the 90th percentile of wages to the 10th percentile to measure inequality. To measure the impact of students, I create two different samples, one with all wage earners and one that excludes students.

In [49]:
a2_all = a2[a2["EMPSTAT"] == 1].sort_values(by="INCWAGE")
a2_ns = a2_all[a2_all["SCHOOL"] != 2]

In [50]:
a2_all["RunningTot"] = a2_all.cumsum()["PERWT"]
a2_all["RunningPct"] = a2_all["RunningTot"]/a2_all["RunningTot"].max()*100

In [51]:
a2_all[a2_all["RunningPct"]>=10]

,YEAR,SAMPLE,SERIAL,CBSERIAL,HHWT,MET2013,GQ,PERNUM,PERWT,SCHOOL,EMPSTAT,EMPSTATD,LABFORCE,INCWAGE,RunningTot,RunningPct
2606,2015,201501,658993,1261168,200,11460,1,3,93,2,1,10,2,3000,18434,10.004776
2199,2015,201501,653684,1079370,78,11460,1,6,150,2,1,12,2,3000,18584,10.086186
339,2015,201501,626751,144067,59,11460,4,1,59,2,1,10,2,3000,18643,10.118208
2515,2015,201501,657931,1225049,7,11460,4,1,7,2,1,10,2,3100,18650,10.122007
2503,2015,201501,657757,1219268,93,11460,1,1,93,1,1,10,2,3100,18743,10.172481
885,2015,201501,634854,425731,50,11460,1,1,51,1,1,10,2,3100,18794,10.200161
2443,2015,201501,657148,1197933,293,11460,1,3,284,2,1,10,2,3300,19078,10.354297
242,2015,201501,625614,106396,128,11460,1,4,120,2,1,10,2,3300,19198,10.419426
422,2015,201501,628401,203084,43,11460,4,1,43,2,1,10,2,3400,19241,10.442763
3084,2015,201501,665598,1487811,94,11460,1,2,88,1,1,10,2,3400,19329,10.490524
1870,2015,201501,648866,912966,191,11460,1,2,240,1,1,10,2,3400,19569,10.620780
601,2015,201501,630991,291735,128,11460,4,1,128,2,1,10,2,3400,19697,10.690250
352,2015,201501,627025,153801,70,11460,1,2,78,1,1,10,2,3500,19775,10.732584
1265,2015,201501,640247,614325,131,11460,4,1,131,2,1,10,2,3500,19906,10.803682
104,2015,201501,623997,52094,77,11460,1,3,240,1,1,10,2,3500,20146,10.933938
1489,2015,201501,643854,739411,96,11460,1,2,86,1,1,10,2,3600,20232,10.980614
2411,2015,201501,656770,1184633,72,11460,1,2,54,1,1,10,2,3600,20286,11.009921
1438,2015,201501,642902,705553,123,11460,1,1,123,1,1,10,2,3700,20409,11.076678
1284,2015,201501,640464,622733,83,11460,1,1,83,1,1,10,2,3700,20492,11.121725
1045,2015,201501,637380,513158,189,11460,1,2,214,1,1,10,2,3700,20706,11.237870
2137,2015,201501,652946,1054214,115,11460,1,1,114,2,1,10,2,3800,20820,11.299742
949,2015,201501,635686,455879,170,11460,1,2,119,2,1,10,2,4000,20939,11.364327
1263,2015,201501,640197,612739,117,11460,1,5,93,1,1,10,2,4000,21032,11.414801
3025,2015,201501,664444,1448003,63,11460,4,1,63,2,1,10,2,4000,21095,11.448994
2724,2015,201501,660459,1312181,119,11460,1,1,119,1,1,10,2,4000,21214,11.513579
3069,2015,201501,665084,1470569,73,11460,2,3,87,2,1,10,2,4000,21301,11.560797
379,2015,201501,627593,172845,94,11460,1,4,128,1,1,10,2,4000,21429,11.630267
750,2015,201501,633049,362781,90,11460,1,3,160,2,1,10,2,4000,21589,11.717105
2325,2015,201501,655478,1140132,100,11460,1,4,112,1,1,10,2,4000,21701,11.777891
1762,2015,201501,647375,861039,68,11460,4,1,68,2,1,10,2,4000,21769,11.814797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2230,2015,201501,654059,1092581,18,11460,1,2,13,1,1,10,2,382000,181940,98.745197
571,2015,201501,630538,276779,52,11460,1,1,53,2,1,10,2,382000,181993,98.773962
950,2015,201501,635698,456334,123,11460,1,1,124,1,1,10,2,382000,182117,98.841261
1034,2015,201501,637319,511498,116,11460,1,2,91,1,1,10,2,382000,182208,98.890650
2427,2015,201501,656948,1190525,93,11460,1,1,93,1,1,10,2,382000,182301,98.941124
2954,2015,201501,663557,1416442,93,11460,1,1,93,1,1,10,2,382000,182394,98.991598
904,2015,201501,635066,432926,52,11460,1,1,53,1,1,10,2,382000,182447,99.020363
2582,2015,201501,658796,1254251,60,11460,1,1,60,1,1,10,2,382000,182507,99.052928
1199,2015,201501,639358,582967,90,11460,1,1,89,1,1,10,2,382000,182596,99.101231
1201,2015,201501,639364,583350,150,11460,1,2,161,1,1,10,2,382000,182757,99.188611
2583,2015,201501,658796,1254251,60,11460,1,2,55,1,1,10,2,382000,182812,99.218462
1277,2015,201501,640373,619540,158,11460,1,1,158,1,1,10,2,382000,182970,99.304214
1328,2015,201501,641208,648283,109,11460,1,1,110,1,1,10,2,382000,183080,99.363915
1344,2015,201501,641512,659375,90,11460,1,2,90,1,1,10,2,382000,183170,99.412761
1714,2015,201501,646804,841455,51,11460,1,1,51,1,1,10,2,382000,183221,99.440440
1352,2015,201501,641689,665247,65,11460,1,1,65,1,1,10,2,382000,183286,99.475718
791,2015,201501,633608,382703,12,11460,1,2,14,1,1,10,2,382000,183300,99.483316
790,2015,201501,633608,382703,12,11460,1,1,13,1,1,10,2,382000,183313,99.490372
1481,2015,201501,643680,733390,55,11460,1,1,55,1,1,10,2,382000,183368,99.520222
694,2015,201501,632424,341478,52,11460,1,1,53,1,1,10,2,382000,183421,99.548987
680,2015,201501,632222,334869,89,11460,1,2,110,1,1,10,2,382000,183531,99.608688
154,2015,201501,624518,69893,67,11460,1,1,67,1,1,10,2,382000,183598,99.645051
2234,2015,201501,654137,1094862,46,11460,1,1,46,1,1,10,2,382000,183644,99.670017
679,2015,201501,632222,334869,89,11460,1,1,89,1,1,10,2,382000,183733,99.718321
637,2015,201501,631581,312245,14,11460,1,2,17,1,1,10,2,382000,183750,99.727547
3059,2015,201501,664990,1467764,130,11460,1,1,130,1,1,10,2,382000,183880,99.798103
1584,2015,201501,645137,782757,74,11460,1,2,49,1,1,10,2,382000,183929,99.824697
447,2015,201501,628798,216476,97,11460,1,2,84,1,1,10,2,382000,184013,99.870286
1357,2015,201501,641932,673005,52,11460,1,1,52,1,1,10,2,382000,184065,99.898509
2988,2015,201501,664033,1433447,186,11460,1,1,187,1,1,10,2,382000,184252,100.000000

In [52]:
a2_all[a2_all["RunningPct"]>=90]

,YEAR,SAMPLE,SERIAL,CBSERIAL,HHWT,MET2013,GQ,PERNUM,PERWT,SCHOOL,EMPSTAT,EMPSTATD,LABFORCE,INCWAGE,RunningTot,RunningPct
452,2015,201501,628909,220585,106,11460,1,1,106,1,1,10,2,104000,165856,90.015848
921,2015,201501,635459,448262,144,11460,1,1,144,1,1,10,2,105000,166000,90.094002
2656,2015,201501,659450,1276867,65,11460,1,2,52,1,1,10,2,105000,166052,90.122224
2727,2015,201501,660499,1313367,93,11460,1,1,93,1,1,10,2,105000,166145,90.172698
1471,2015,201501,643453,724558,133,11460,1,1,132,1,1,10,2,107000,166277,90.244339
998,2015,201501,636431,481466,95,11460,1,1,95,1,1,10,2,108000,166372,90.295899
2043,2015,201501,651401,1001703,42,11460,1,1,42,1,1,10,2,108000,166414,90.318694
2145,2015,201501,653092,1059469,98,11460,1,2,79,1,1,10,2,108000,166493,90.361570
2442,2015,201501,657148,1197933,293,11460,1,2,231,1,1,10,2,108000,166724,90.486942
1125,2015,201501,638243,544146,27,11460,1,2,27,1,1,10,2,109000,166751,90.501596
200,2015,201501,625191,93183,197,11460,1,2,191,1,1,10,2,110000,166942,90.605258
372,2015,201501,627558,171504,50,11460,1,1,50,1,1,10,2,110000,166992,90.632395
2927,2015,201501,663209,1404570,74,11460,1,1,74,1,1,10,2,110000,167066,90.672557
765,2015,201501,633312,372144,49,11460,1,1,49,1,1,10,2,110000,167115,90.699151
597,2015,201501,630952,290166,149,11460,1,1,149,1,1,10,2,110000,167264,90.780019
1552,2015,201501,644823,772203,96,11460,1,1,96,1,1,10,2,112000,167360,90.832121
2686,2015,201501,660000,1295931,93,11460,1,1,93,1,1,10,2,113000,167453,90.882596
979,2015,201501,636041,468119,158,11460,1,1,158,1,1,10,2,113000,167611,90.968348
3086,2015,201501,665629,1488974,83,11460,1,2,83,1,1,10,2,114000,167694,91.013395
0,2015,201501,622532,2076,409,11460,1,1,409,1,1,10,2,114000,168103,91.235373
963,2015,201501,635928,464044,95,11460,1,2,45,1,1,10,2,115000,168148,91.259796
175,2015,201501,624850,80276,162,11460,1,1,162,1,1,10,2,115000,168310,91.347719
205,2015,201501,625225,93994,104,11460,1,2,75,1,1,10,2,115000,168385,91.388425
914,2015,201501,635257,440298,36,11460,1,1,35,1,1,10,2,115000,168420,91.407420
330,2015,201501,626686,141961,69,11460,1,2,55,1,1,10,2,115000,168475,91.437271
2704,2015,201501,660193,1302776,30,11460,1,2,29,1,1,10,2,116000,168504,91.453010
2101,2015,201501,652378,1035113,163,11460,1,2,133,1,1,10,2,117000,168637,91.525194
1879,2015,201501,648927,915200,99,11460,1,1,99,1,1,10,2,117000,168736,91.578925
1568,2015,201501,644955,776472,158,11460,1,1,159,1,1,10,2,120000,168895,91.665219
2887,2015,201501,662597,1384786,100,11460,1,2,97,1,1,10,2,120000,168992,91.717865
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2230,2015,201501,654059,1092581,18,11460,1,2,13,1,1,10,2,382000,181940,98.745197
571,2015,201501,630538,276779,52,11460,1,1,53,2,1,10,2,382000,181993,98.773962
950,2015,201501,635698,456334,123,11460,1,1,124,1,1,10,2,382000,182117,98.841261
1034,2015,201501,637319,511498,116,11460,1,2,91,1,1,10,2,382000,182208,98.890650
2427,2015,201501,656948,1190525,93,11460,1,1,93,1,1,10,2,382000,182301,98.941124
2954,2015,201501,663557,1416442,93,11460,1,1,93,1,1,10,2,382000,182394,98.991598
904,2015,201501,635066,432926,52,11460,1,1,53,1,1,10,2,382000,182447,99.020363
2582,2015,201501,658796,1254251,60,11460,1,1,60,1,1,10,2,382000,182507,99.052928
1199,2015,201501,639358,582967,90,11460,1,1,89,1,1,10,2,382000,182596,99.101231
1201,2015,201501,639364,583350,150,11460,1,2,161,1,1,10,2,382000,182757,99.188611
2583,2015,201501,658796,1254251,60,11460,1,2,55,1,1,10,2,382000,182812,99.218462
1277,2015,201501,640373,619540,158,11460,1,1,158,1,1,10,2,382000,182970,99.304214
1328,2015,201501,641208,648283,109,11460,1,1,110,1,1,10,2,382000,183080,99.363915
1344,2015,201501,641512,659375,90,11460,1,2,90,1,1,10,2,382000,183170,99.412761
1714,2015,201501,646804,841455,51,11460,1,1,51,1,1,10,2,382000,183221,99.440440
1352,2015,201501,641689,665247,65,11460,1,1,65,1,1,10,2,382000,183286,99.475718
791,2015,201501,633608,382703,12,11460,1,2,14,1,1,10,2,382000,183300,99.483316
790,2015,201501,633608,382703,12,11460,1,1,13,1,1,10,2,382000,183313,99.490372
1481,2015,201501,643680,733390,55,11460,1,1,55,1,1,10,2,382000,183368,99.520222
694,2015,201501,632424,341478,52,11460,1,1,53,1,1,10,2,382000,183421,99.548987
680,2015,201501,632222,334869,89,11460,1,2,110,1,1,10,2,382000,183531,99.608688
154,2015,201501,624518,69893,67,11460,1,1,67,1,1,10,2,382000,183598,99.645051
2234,2015,201501,654137,1094862,46,11460,1,1,46,1,1,10,2,382000,183644,99.670017
679,2015,201501,632222,334869,89,11460,1,1,89,1,1,10,2,382000,183733,99.718321
637,2015,201501,631581,312245,14,11460,1,2,17,1,1,10,2,382000,183750,99.727547
3059,2015,201501,664990,1467764,130,11460,1,1,130,1,1,10,2,382000,183880,99.798103
1584,2015,201501,645137,782757,74,11460,1,2,49,1,1,10,2,382000,183929,99.824697
447,2015,201501,628798,216476,97,11460,1,2,84,1,1,10,2,382000,184013,99.870286
1357,2015,201501,641932,673005,52,11460,1,1,52,1,1,10,2,382000,184065,99.898509
2988,2015,201501,664033,1433447,186,11460,1,1,187,1,1,10,2,382000,184252,100.000000

In [53]:
104000/3000

34.666666666666664

This puts the 90/10 ratio at 34.67, well above the 6.6 given in the report.

In [54]:
a2_ns["RunningTot"] = a2_ns.cumsum()["PERWT"]
a2_ns["RunningPct"] = a2_ns["RunningTot"]/a2_ns["RunningTot"].max()*100

C:\Users\bjr21\Anaconda3\envs\census\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\bjr21\Anaconda3\envs\census\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [55]:
a2_ns[a2_ns["RunningPct"]>=10]

,YEAR,SAMPLE,SERIAL,CBSERIAL,HHWT,MET2013,GQ,PERNUM,PERWT,SCHOOL,EMPSTAT,EMPSTATD,LABFORCE,INCWAGE,RunningTot,RunningPct
332,2015,201501,626686,141961,69,11460,1,4,99,1,1,10,2,7000,14611,10.013364
1605,2015,201501,645614,798129,80,11460,1,1,81,1,1,10,2,7000,14692,10.068876
1072,2015,201501,637649,522715,41,11460,1,2,48,1,1,10,2,7000,14740,10.101772
520,2015,201501,629771,250304,93,11460,1,2,119,1,1,10,2,7000,14859,10.183326
2759,2015,201501,660712,1321006,26,11460,1,2,28,1,1,10,2,7000,14887,10.202515
2065,2015,201501,651919,1018693,168,11460,1,1,167,1,1,10,2,7200,15054,10.316965
2453,2015,201501,657254,1202403,134,11460,1,1,134,1,1,10,2,7400,15188,10.408800
2356,2015,201501,655995,1157833,155,11460,1,2,156,1,1,10,2,7800,15344,10.515711
2228,2015,201501,654037,1091831,94,11460,1,2,100,1,1,10,2,7800,15444,10.584244
187,2015,201501,625111,90330,64,11460,1,1,64,1,1,10,2,7900,15508,10.628105
2358,2015,201501,656039,1159370,84,11460,1,2,92,1,1,10,2,8000,15600,10.691156
654,2015,201501,631986,326322,101,11460,1,1,101,1,1,10,2,8000,15701,10.760374
2052,2015,201501,651667,1010371,76,11460,1,1,76,1,1,10,2,8000,15777,10.812459
1235,2015,201501,639785,597742,76,11460,1,1,77,1,1,10,2,8000,15854,10.865230
21,2015,201501,622773,11099,65,11460,1,1,64,1,1,10,2,8100,15918,10.909091
1817,2015,201501,647983,882586,182,11460,1,4,126,1,1,10,2,8100,16044,10.995443
580,2015,201501,630656,280366,42,11460,1,1,43,1,1,10,2,8200,16087,11.024912
1327,2015,201501,641194,647698,110,11460,1,1,110,1,1,10,2,8200,16197,11.100298
366,2015,201501,627346,165172,143,11460,1,2,141,1,1,10,2,8400,16338,11.196930
672,2015,201501,632165,332470,83,11460,1,1,83,1,1,10,2,8400,16421,11.253812
67,2015,201501,623367,31591,155,11460,1,1,155,1,1,10,2,8500,16576,11.360038
1146,2015,201501,638746,560879,106,11460,1,1,106,1,1,10,2,9000,16682,11.432683
999,2015,201501,636431,481466,95,11460,1,2,93,1,1,10,2,9000,16775,11.496419
2739,2015,201501,660583,1316248,114,11460,1,3,123,1,1,10,2,9000,16898,11.580715
3060,2015,201501,664990,1467764,130,11460,1,2,114,1,1,10,2,9500,17012,11.658842
190,2015,201501,625111,90330,64,11460,1,4,71,1,1,10,2,9600,17083,11.707501
2551,2015,201501,658392,1240140,77,11460,1,3,66,1,1,10,2,9600,17149,11.752733
2701,2015,201501,660190,1302697,271,11460,1,1,272,1,1,10,2,9900,17421,11.939143
1641,2015,201501,646126,816772,123,11460,1,1,123,1,1,10,2,10000,17544,12.023438
1217,2015,201501,639539,589731,15,11460,4,1,15,1,1,10,2,10000,17559,12.033718
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,2015,201501,629020,224363,95,11460,1,1,94,1,1,10,2,382000,143643,98.442929
2230,2015,201501,654059,1092581,18,11460,1,2,13,1,1,10,2,382000,143656,98.451838
950,2015,201501,635698,456334,123,11460,1,1,124,1,1,10,2,382000,143780,98.536819
1034,2015,201501,637319,511498,116,11460,1,2,91,1,1,10,2,382000,143871,98.599184
2427,2015,201501,656948,1190525,93,11460,1,1,93,1,1,10,2,382000,143964,98.662920
2954,2015,201501,663557,1416442,93,11460,1,1,93,1,1,10,2,382000,144057,98.726656
904,2015,201501,635066,432926,52,11460,1,1,53,1,1,10,2,382000,144110,98.762978
2582,2015,201501,658796,1254251,60,11460,1,1,60,1,1,10,2,382000,144170,98.804098
1199,2015,201501,639358,582967,90,11460,1,1,89,1,1,10,2,382000,144259,98.865093
1201,2015,201501,639364,583350,150,11460,1,2,161,1,1,10,2,382000,144420,98.975431
2583,2015,201501,658796,1254251,60,11460,1,2,55,1,1,10,2,382000,144475,99.013124
1277,2015,201501,640373,619540,158,11460,1,1,158,1,1,10,2,382000,144633,99.121406
1328,2015,201501,641208,648283,109,11460,1,1,110,1,1,10,2,382000,144743,99.196793
1344,2015,201501,641512,659375,90,11460,1,2,90,1,1,10,2,382000,144833,99.258472
1714,2015,201501,646804,841455,51,11460,1,1,51,1,1,10,2,382000,144884,99.293424
1352,2015,201501,641689,665247,65,11460,1,1,65,1,1,10,2,382000,144949,99.337971
791,2015,201501,633608,382703,12,11460,1,2,14,1,1,10,2,382000,144963,99.347565
790,2015,201501,633608,382703,12,11460,1,1,13,1,1,10,2,382000,144976,99.356475
1481,2015,201501,643680,733390,55,11460,1,1,55,1,1,10,2,382000,145031,99.394168
694,2015,201501,632424,341478,52,11460,1,1,53,1,1,10,2,382000,145084,99.430490
680,2015,201501,632222,334869,89,11460,1,2,110,1,1,10,2,382000,145194,99.505877
154,2015,201501,624518,69893,67,11460,1,1,67,1,1,10,2,382000,145261,99.551794
2234,2015,201501,654137,1094862,46,11460,1,1,46,1,1,10,2,382000,145307,99.583319
679,2015,201501,632222,334869,89,11460,1,1,89,1,1,10,2,382000,145396,99.644313
637,2015,201501,631581,312245,14,11460,1,2,17,1,1,10,2,382000,145413,99.655964
3059,2015,201501,664990,1467764,130,11460,1,1,130,1,1,10,2,382000,145543,99.745057
1584,2015,201501,645137,782757,74,11460,1,2,49,1,1,10,2,382000,145592,99.778638
447,2015,201501,628798,216476,97,11460,1,2,84,1,1,10,2,382000,145676,99.836206
1357,2015,201501,641932,673005,52,11460,1,1,52,1,1,10,2,382000,145728,99.871843
2988,2015,201501,664033,1433447,186,11460,1,1,187,1,1,10,2,382000,145915,100.000000

In [56]:
a2_all[a2_all["RunningPct"]>=90]

,YEAR,SAMPLE,SERIAL,CBSERIAL,HHWT,MET2013,GQ,PERNUM,PERWT,SCHOOL,EMPSTAT,EMPSTATD,LABFORCE,INCWAGE,RunningTot,RunningPct
452,2015,201501,628909,220585,106,11460,1,1,106,1,1,10,2,104000,165856,90.015848
921,2015,201501,635459,448262,144,11460,1,1,144,1,1,10,2,105000,166000,90.094002
2656,2015,201501,659450,1276867,65,11460,1,2,52,1,1,10,2,105000,166052,90.122224
2727,2015,201501,660499,1313367,93,11460,1,1,93,1,1,10,2,105000,166145,90.172698
1471,2015,201501,643453,724558,133,11460,1,1,132,1,1,10,2,107000,166277,90.244339
998,2015,201501,636431,481466,95,11460,1,1,95,1,1,10,2,108000,166372,90.295899
2043,2015,201501,651401,1001703,42,11460,1,1,42,1,1,10,2,108000,166414,90.318694
2145,2015,201501,653092,1059469,98,11460,1,2,79,1,1,10,2,108000,166493,90.361570
2442,2015,201501,657148,1197933,293,11460,1,2,231,1,1,10,2,108000,166724,90.486942
1125,2015,201501,638243,544146,27,11460,1,2,27,1,1,10,2,109000,166751,90.501596
200,2015,201501,625191,93183,197,11460,1,2,191,1,1,10,2,110000,166942,90.605258
372,2015,201501,627558,171504,50,11460,1,1,50,1,1,10,2,110000,166992,90.632395
2927,2015,201501,663209,1404570,74,11460,1,1,74,1,1,10,2,110000,167066,90.672557
765,2015,201501,633312,372144,49,11460,1,1,49,1,1,10,2,110000,167115,90.699151
597,2015,201501,630952,290166,149,11460,1,1,149,1,1,10,2,110000,167264,90.780019
1552,2015,201501,644823,772203,96,11460,1,1,96,1,1,10,2,112000,167360,90.832121
2686,2015,201501,660000,1295931,93,11460,1,1,93,1,1,10,2,113000,167453,90.882596
979,2015,201501,636041,468119,158,11460,1,1,158,1,1,10,2,113000,167611,90.968348
3086,2015,201501,665629,1488974,83,11460,1,2,83,1,1,10,2,114000,167694,91.013395
0,2015,201501,622532,2076,409,11460,1,1,409,1,1,10,2,114000,168103,91.235373
963,2015,201501,635928,464044,95,11460,1,2,45,1,1,10,2,115000,168148,91.259796
175,2015,201501,624850,80276,162,11460,1,1,162,1,1,10,2,115000,168310,91.347719
205,2015,201501,625225,93994,104,11460,1,2,75,1,1,10,2,115000,168385,91.388425
914,2015,201501,635257,440298,36,11460,1,1,35,1,1,10,2,115000,168420,91.407420
330,2015,201501,626686,141961,69,11460,1,2,55,1,1,10,2,115000,168475,91.437271
2704,2015,201501,660193,1302776,30,11460,1,2,29,1,1,10,2,116000,168504,91.453010
2101,2015,201501,652378,1035113,163,11460,1,2,133,1,1,10,2,117000,168637,91.525194
1879,2015,201501,648927,915200,99,11460,1,1,99,1,1,10,2,117000,168736,91.578925
1568,2015,201501,644955,776472,158,11460,1,1,159,1,1,10,2,120000,168895,91.665219
2887,2015,201501,662597,1384786,100,11460,1,2,97,1,1,10,2,120000,168992,91.717865
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2230,2015,201501,654059,1092581,18,11460,1,2,13,1,1,10,2,382000,181940,98.745197
571,2015,201501,630538,276779,52,11460,1,1,53,2,1,10,2,382000,181993,98.773962
950,2015,201501,635698,456334,123,11460,1,1,124,1,1,10,2,382000,182117,98.841261
1034,2015,201501,637319,511498,116,11460,1,2,91,1,1,10,2,382000,182208,98.890650
2427,2015,201501,656948,1190525,93,11460,1,1,93,1,1,10,2,382000,182301,98.941124
2954,2015,201501,663557,1416442,93,11460,1,1,93,1,1,10,2,382000,182394,98.991598
904,2015,201501,635066,432926,52,11460,1,1,53,1,1,10,2,382000,182447,99.020363
2582,2015,201501,658796,1254251,60,11460,1,1,60,1,1,10,2,382000,182507,99.052928
1199,2015,201501,639358,582967,90,11460,1,1,89,1,1,10,2,382000,182596,99.101231
1201,2015,201501,639364,583350,150,11460,1,2,161,1,1,10,2,382000,182757,99.188611
2583,2015,201501,658796,1254251,60,11460,1,2,55,1,1,10,2,382000,182812,99.218462
1277,2015,201501,640373,619540,158,11460,1,1,158,1,1,10,2,382000,182970,99.304214
1328,2015,201501,641208,648283,109,11460,1,1,110,1,1,10,2,382000,183080,99.363915
1344,2015,201501,641512,659375,90,11460,1,2,90,1,1,10,2,382000,183170,99.412761
1714,2015,201501,646804,841455,51,11460,1,1,51,1,1,10,2,382000,183221,99.440440
1352,2015,201501,641689,665247,65,11460,1,1,65,1,1,10,2,382000,183286,99.475718
791,2015,201501,633608,382703,12,11460,1,2,14,1,1,10,2,382000,183300,99.483316
790,2015,201501,633608,382703,12,11460,1,1,13,1,1,10,2,382000,183313,99.490372
1481,2015,201501,643680,733390,55,11460,1,1,55,1,1,10,2,382000,183368,99.520222
694,2015,201501,632424,341478,52,11460,1,1,53,1,1,10,2,382000,183421,99.548987
680,2015,201501,632222,334869,89,11460,1,2,110,1,1,10,2,382000,183531,99.608688
154,2015,201501,624518,69893,67,11460,1,1,67,1,1,10,2,382000,183598,99.645051
2234,2015,201501,654137,1094862,46,11460,1,1,46,1,1,10,2,382000,183644,99.670017
679,2015,201501,632222,334869,89,11460,1,1,89,1,1,10,2,382000,183733,99.718321
637,2015,201501,631581,312245,14,11460,1,2,17,1,1,10,2,382000,183750,99.727547
3059,2015,201501,664990,1467764,130,11460,1,1,130,1,1,10,2,382000,183880,99.798103
1584,2015,201501,645137,782757,74,11460,1,2,49,1,1,10,2,382000,183929,99.824697
447,2015,201501,628798,216476,97,11460,1,2,84,1,1,10,2,382000,184013,99.870286
1357,2015,201501,641932,673005,52,11460,1,1,52,1,1,10,2,382000,184065,99.898509
2988,2015,201501,664033,1433447,186,11460,1,1,187,1,1,10,2,382000,184252,100.000000

In [57]:
104000/7000

14.857142857142858

This puts the 90/10 wage ratio at 14.9, still above what was reported in the paper.